id = "google-apps-script"
name = "Google Apps Script"
version = "1.0.0"
schema_version = 1
authors = ["Jonathan Kyamogi"]
description = "Google Apps Script support"
repository = "https://github.com/jkyamogi/zed-gas-lsp.git"

[language_servers.google-apps-script]
name = "Google Apps Script"
languages = ["Google Apps Script"]

[language_servers.google-apps-script.language_ids]
"Google Apps Script" = "javascript"
